# coding: utf-8
"""Paired copy for the reconstructed field guide. Scene types are recollections;
specific questions, prompts and operating rules are proposed in this edition.
"""
COPY = {
'zh': {
 'titles':['帮助观众留下自己的看法','区域与反馈任务地图','让操作提示对应实际界面','帮助表达，不替人作答','先分清状态，再恢复连接','结果不明确时，不重复提交','现场记要点，负责人跟进','展前配置与培训说明'],
 'kickers':['01 / 服务与职责','02 / 找到自己的区域','03 / 标准操作','04 / 六张引导卡','05 / 入口与连接','06 / 表达与完成','07 / 记录与交接','08 / 展前准备'],
 'subs':['展前读 01-03、08；现场查 04-06 或单页速查；记录与交接用 07。','先找到反馈对象，再核对对应物料与手机页面。','工作人员解释操作，观众决定内容；以下为当前演示界面的局部。','先听，再给一次中性提示；接受原有回答，也允许随时结束。','先问：有没有写下内容？有没有点过提交？不要一律刷新重试。','按可见状态处理；只有已确认安全时，才邀请观众重试。','用于抽样体验和需跟进的问题，不要求每位观众填写完整记录。','负责人补齐配置并确认拟定规则，再用于现场；培训先说明演示范围。'],
 'source_title':'关于这份指南',
 'source':'依据参与经历与项目回忆重建，2026。整体体验、产品、座谈 / 演讲三类场景来自项目回忆；具体问题、话术和处理规则为本次拟定。原始手册未保留，本版不是历史原件。',
 'flow_title':'服务关系与职责',
 'flow':[('工作人员','邀请参与'),('观众','进入对应入口'),('观众','表达反馈'),('观众','核对与完成'),('后台团队','接收与分析')],
 'invitation_title':'先说明用途，再给选择',
 'invitation':'“我们想了解您对[当前区域 / 产品 / 活动]的看法。愿意的话，可以轻触 NFC 卡或扫码，用语音或文字留下意见。不参加也完全没关系。”',
 'roles_title':'谁负责什么',
 'roles':[['观众','决定是否参与、表达什么、如何修改及何时结束。'],['工作人员','确认反馈对象、解释问题与操作；不代答、不改写评价。'],['现场负责人','核对入口、协调异常、接收记录并安排跟进。'],['后台团队','核查接收状态与系统问题，负责后续分析。']],
 'purpose_note':'只使用负责人确认的用途说明；不自行承诺匿名、奖励、耗时或客户回应。模拟培训说明集中在第 08 节。',
 'regions':[
  ['A','整体体验','展会整体；任选最有感受的一点。','区域与参观环节','这次参观，您最想反馈什么？','在哪个环节？'],
  ['P','具体产品','眼前这件产品；区分第一印象与使用经验。','产品名称与图片','您对这件产品有什么看法？','第一印象，还是使用经验？'],
  ['T','座谈 / 演讲','具体活动场次；内容、理解或参与体验。','活动标题、场次或时间','关于这场活动，您最想反馈什么？','哪一部分让您这样想？']],
 'region_labels':['评价什么','先确认','可以这样问'],
 'region_note':'A / P / T 为本指南的分类代号；具体区域名、问题与入口由负责人配置。',
 'region_check_title':'值守前核对 / 一区一份',
 'region_check':'我的区域：________________  反馈对象：________________\n物料编号：________________  页面对象：________________\n已核实备用入口：_____________________________________\n区域联系人 / 渠道：___________________________________',
 'match_title':'实物或活动牌 → 触点物料 → 手机页面',
 'match':'三处对象与问题应一致。若不对应，暂停该物料的邀请，通知负责人；不要让观众在错误页面继续填写。',
 'steps_intro':'先用第 01 节话术邀请；进入后核对产品或活动名称，再由观众选择表达方式。',
 'steps':[
  ['01 / 表达方式由观众选择','Try speaking 是语音入口，Write a thought 是文字入口。不方便开口时，可直接选择文字。','home.png',(0,490,390,800)],
  ['02 / 核对与修改自己的内容','请观众确认文字是否表达本意。Edit 修改内容；Continue as text 保留文字并继续编辑。工作人员只说明按钮用途。','review.png',(0,215,390,765)],
  ['03 / 结束前看清结果','按已确认的完成提示判断。当前截图的 Demo complete 仅表示演示结束；真实接收不明确时，按 E6 处理。','complete.png',(0,225,390,615)]],
 'protect_title':'遇到清空、重录或重启确认',
 'protect':'先说明可能替换或丢失内容，再由观众决定。不要为了恢复界面而擅自刷新、清空或代点提交。',
 'cards':[
  ['不知道 YouFeed 是什么','说明用途与参与方式。','这是一个反馈入口，帮助我们了解您对这里的看法。是否参加由您决定。','只介绍已确认的用途，不承诺奖励或意见一定获采纳。'],
  ['不知道该评价什么','确认对象，缩小范围。','这里对应[对象]。您可以只说最有感受的一点。','不提供示例答案，不说“可以夸一下设计”。'],
  ['“没意见”或评价笼统','提供一次自愿补充的机会。','如果愿意，可以说说为什么；不补充也可以。','不反复追问，不将“还行”改写成好评。'],
  ['不方便使用语音','直接提供文字选择。','您可以选择文字输入，按自己的方式写。','不要求先开麦，不代录、不代答。'],
  ['进入错误对象页面','停止错配，核对入口。','您想评价的是[目标对象]，对吗？我们先核对入口。','不在错误页面硬填；已有文字先说明丢失风险。'],
  ['不愿参与或想结束','尊重退出，结束协助。','好的，谢谢您，您可以随时结束。','不劝留、不追问原因、不替其完成。']],
 'card_labels':['目的','可说','避免'],
 'entry_branches':[['尚未填写','核对入口 / 网络','#245B78'],['已写，未提交','保留原页 → E1','#276047'],['已提交 / 不确定','不重复提交 → E6','#E0001B']],
 'status_branches':[['语音不可用','转文字 → E4','#245B78'],['明确失败','安全重试？→ E5','#276047'],['接收不明确','不重复提交 → E6','#E0001B']],
 'incidents':[
  ['E1 / 网络不稳定或页面打不开',[
   ['先问','确认是否已有文字、是否点过提交，再检查网络与入口。'],
   ['未填写','可自愿切换可用网络，重新打开已核实入口。'],
   ['已写未交','保留原页，不刷新、不清空。告知观众内容尚未提交；按已确认的草稿恢复方式处理，或由观众选择结束。不要转去核查接收。'],
   ['已提交','若已点提交或无法确认，转 E6；不重新打开重复提交。'],
   ['停止 / 交接','一次有变化的恢复尝试仍失败，或观众想结束，就停止。记入口、状态与尝试结果，交现场负责人。']]],
  ['E2 / NFC 或二维码无法打开',[
   ['先查','核对卡片对象、二维码遮挡和目标链接。'],
   ['替代','NFC 失败可用同对象已核实二维码；二维码失败，仅用负责人提供并核实的备用入口。'],
   ['停止 / 交接','替代入口仍失败或没有备用入口，就停止；记触点编号与现象，交负责人核对物料。']]],
  ['E3 / 页面对象不对应',[
   ['先查','对照实物 / 活动牌、物料和手机页面，停止填写。'],
   ['替代','未填写时转正确入口；已有文字先说明重新打开可能丢失，不承诺自动迁移。'],
   ['停止 / 交接','找不到正确入口或仍错配，暂停该物料；记错误与目标对象，交负责人处理。']]],
  ['E4 / 语音不可用或转写失败',[
   ['先查','读取页面提示，确认是否已有文字。'],
   ['替代','提供文字输入；按页面提示保留已有内容。仅在该版本已确认支持时尝试语音恢复。'],
   ['停止 / 交接','一次恢复仍失败或观众不愿继续，转文字或结束；记录提示和切换结果，交负责人。']]],
  ['E5 / 明确显示提交失败',[
   ['先查','读取错误提示，按负责人确认的失败语义判断；报错不一定意味着后台未接收。'],
   ['替代','仅在该错误已确认可安全重试时，由观众选择重试。'],
   ['停止 / 交接','一次安全重试仍失败，或接收状态不确定，转 E6。记时间、重试次数及最后状态，交负责人。']]],
  ['E6 / 已提交，但接收状态不明确',[
   ['先查','确认最后动作和页面状态；无成功提示不能直接视为未提交。'],
   ['当场','原页仍在就保留，不刷新、不重开重复提交。说明结果暂不明确，允许观众结束等待。'],
   ['停止 / 交接','不继续试交。记时间、入口、最后动作及系统回执号（如有），由负责人交后台核查。'],
   ['状态','记录“结果不明确”，核查后再更新；没有确认机制时，不向观众声称已接收。']]]],
 'incident_note':'所有恢复规则由负责人在第 08 节确认；未确认的能力不作现场承诺。',
 'record_staff_title':'A / 工作人员快速记录',
 'record_staff':[['记录项','现场填写'],['时间与对象','时间：________  区域 / 入口：________________\n反馈对象：________________________________'],['发生什么 / 如何协助','问题或必要原话：__________________________\n采取的协助 / 重试次数：_____________________'],['完成情况','□ 独立完成  □ 协助后完成  □ 未完成  □ 不明确\n最后页面状态：____________________________'],['交接','需跟进：□ 是  □ 否  交给谁：_______________\n记录人工作代号：________  记录编号：________']],
 'record_note':'统一邀请不计“协助”；额外解释、提示或排障计入。不需要姓名、电话或完整反馈内容。',
 'record_lead_title':'B / 负责人跟进区',
 'record_lead':[['跟进项','负责人填写'],['接收与分派','接收人 / 时间：____________________________\n交技术 / 后台 / 内容负责人：________________'],['核实与关闭','真实接收：□ 已核实  □ 未核实  □ 不适用\n□ 待处理  □ 处理中  □ 已关闭\n下次回查：________  结果依据：_______________']],
 'handoff':'入口 / 网络 / 语音故障交技术支持；接收状态交后台；对象与问题文案交区域负责人。重复故障或对象错配及时上报；其余按班次交接，接收人确认后续处理。',
 'setup':[['配置项','负责人确认'],['人员与联系','现场负责人 / 备援：________________________\n技术 / 后台 / 内容联系人：__________________'],['入口与恢复','区域入口、备用链接、真实完成提示已核对：___\n草稿恢复方式、安全重试、等待上限：_________'],['记录与用途','记录位置 / 访问范围 / 保存期限：____________\n对外用途说明与确认人：_____________________']],
 'demo_title':'培训使用当前演示时，先说清楚',
 'demo':'“这次是模拟体验，语音使用样例，内容不会送出。”当前界面只展示产品反馈，不包含全部区域入口；不采集真实音频，不连接企业平台。页内切换保留文字，刷新 / 重启会清空，新语音样例可能替换原稿。',
 'walk_title':'三种情境走查',
 'walk':['新人抽一个区域，找对对象和入口，并说出自愿参与的邀请。','观众不知道怎么答：找到对应引导卡，提供中性提示。','已写但未提交就断网：走 E1；已提交却没结果：走 E6。'],
 'walk_log':'日期：________  参与者：________\n每题：□ 找到  □ 需提示  □ 未找到\n需修改：________________  负责人 / 复查：____________',
 'quick_title':'看到什么，下一步做什么',
 'quick_sub':'现场速查 / 详细处理见对应 E 编号；先核对区域和反馈对象。',
 'quick_rows':[['看到什么','当场怎么做','何时交给谁'],['入口打不开，未填写','核对对象与网络，试一次已核实备用入口。E1 / E2','仍失败就停止，找现场负责人。'],['已有文字，尚未提交','保留原页，不刷新；按已确认方式恢复，或由观众结束。E1','无可用恢复方式，记状态交负责人；不查接收。'],['已提交，结果不明','不重复提交；保留原页，允许结束等待。E6','记时间、入口、最后动作，由负责人交后台。'],['对象错误','停止填写，核对正确入口；已有内容先说明风险。E3','仍错配或没有正确入口，暂停物料，找负责人。'],['语音不可用','提供文字；一次恢复仍失败就转文字或结束。E4','记提示和结果，交负责人 / 技术支持。'],['明确提交失败','仅在已确认安全时重试一次；不明确则走 E6。E5','仍失败交负责人，接收核查由后台处理。']],
 'quick_prompt':'不知道说什么：“您可以只说最有感受的一点。”愿意时再问：“是什么让您这样想？”不代答、不诱导、不要求补充。',
 'quick_end':'记时间、区域 / 入口、困难、协助及最后状态。负责人 / 渠道：________________\n演示培训：样例语音、不发送反馈；刷新会清空文字。现场配置见第 08 节。'
},
'en': {
 'titles':['Help visitors share their views','Area & feedback task map','Connect prompts to controls','Support their own words','Check the state before recovery','Unclear receipt? Do not resubmit.','Note on site. Follow up later.','Prepare before field use'],
 'kickers':['01 / PURPOSE & ROLES','02 / FIND YOUR AREA','03 / STANDARD STEPS','04 / SIX PROMPT CARDS','05 / ENTRY & CONNECTION','06 / EXPRESSION & COMPLETION','07 / RECORD & HANDOVER','08 / PREPARATION'],
 'subs':['Before the event: 01-03 and 08. During a shift: 04-06 or the quick sheet. Use 07 for records.','Identify the feedback subject, then match the material and mobile page.','Staff explain controls; visitors own the words. Crops show the current interface demo.','Listen first. Offer one neutral prompt. Accept the answer, or let the visitor finish.','First ask: is there a draft? Has submit been pressed? Do not refresh every error.','Follow the visible state. Invite a retry only when it is confirmed safe.','For sampled attempts and issues needing follow-up; not a full form for every visitor.','The lead confirms settings and proposed rules before field use. Brief the team on demo limits.'],
 'source_title':'About this guide',
 'source':'Reconstructed from project experience and recollections, 2026. The exhibition, product and talk/session contexts are recalled from the project. Specific questions, prompts and operating rules are newly proposed. The original handbook is unavailable.',
 'flow_title':'Service relationship and roles',
 'flow':[('STAFF','Invite'),('VISITOR','Open the right entry'),('VISITOR','Give feedback'),('VISITOR','Review and finish'),('BACKEND','Receive / analyse')],
 'invitation_title':'Explain the purpose, then offer a choice',
 'invitation':'“We would like your views on [this area / product / session]. If you wish, tap the NFC card or scan the QR code to share them by voice or text. Taking part is entirely optional.”',
 'roles_title':'Who does what',
 'roles':[['Visitor','Chooses whether to join, what to say, what to edit and when to stop.'],['Staff','Checks the subject and explains the task and controls; does not answer or rewrite.'],['Field lead','Checks entries, coordinates issues and accepts follow-up records.'],['Backend','Checks receipt and system issues; owns subsequent analysis.']],
 'purpose_note':'Use the agreed purpose statement. Do not invent promises of anonymity, rewards, timing or responses. Demo training notes are in section 08.',
 'regions':[
  ['A','Overall experience','The exhibition as a whole. Choose one thing that stood out.','Area and visit stage','What would you most like to share about your visit?','At what point?'],
  ['P','Product','This specific product. Distinguish first impressions from use.','Product name and image','What do you think of this product?','A first impression or experience of use?'],
  ['T','Talk / session','This specific session: content, understanding or experience.','Title, session or time','What would you most like to share about this session?','Which part made you feel that way?']],
 'region_labels':['FEEDBACK SUBJECT','CHECK','ASK'],
 'region_note':'A / P / T are category codes in this guide. The lead configures actual names, questions and entries.',
 'region_check_title':'Before your shift / One check per area',
 'region_check':'My area: ______________  Feedback subject: ______________\nMaterial ID: ___________  Page subject: __________________\nVerified backup entry: __________________________________\nArea contact / channel: _________________________________',
 'match_title':'Product or session sign → material → mobile page',
 'match':'The subject and question should match. If they do not, pause invitations at that material and notify the lead. Do not ask visitors to continue on the wrong page.',
 'steps_intro':'Invite using section 01. Check the product or session name on entry, then let the visitor choose how to respond.',
 'steps':[
  ['01 / Let the visitor choose','Try speaking opens voice; Write a thought opens text. Writing is a direct choice when speaking is inconvenient.','home.png',(0,490,390,800)],
  ['02 / Review their own words','Ask whether the text says what they mean. Edit changes the text; Continue as text keeps it for editing. Explain the buttons without rewriting their opinion.','review.png',(0,215,390,765)],
  ['03 / Read the completion state','Use the agreed completion indicator. Demo complete in this screenshot means the simulation ended. For uncertain live receipt, follow E6.','complete.png',(0,225,390,615)]],
 'protect_title':'Before clearing, re-recording or restarting',
 'protect':'Explain that content may be replaced or lost, then let the visitor decide. Do not refresh, clear or submit for them just to recover the interface.',
 'cards':[
  ['What is YouFeed?','Explain purpose and choice.','It is a way to share your views about this place. You can choose whether to take part.','Use the agreed purpose; do not promise rewards or action on every comment.'],
  ['What should I comment on?','Confirm and narrow the subject.','This page is about [subject]. You can share one thing that stood out.','Do not suggest answers or ask them to praise the design.'],
  ['“No comments” / “It’s fine”','Offer one optional follow-up.','If you wish, what made you feel that way? It is fine to leave it there.','Do not keep probing or turn vague words into praise.'],
  ['Voice is inconvenient','Offer writing directly.','You can choose text and write in your own way.','Do not insist on voice, record or answer for them.'],
  ['Wrong product or session','Pause and check the entry.','Did you mean [target subject]? Let us check the entry first.','Do not use the wrong page. Explain loss risks if a draft exists.'],
  ['They want to stop','Respect the decision to leave.','Of course. Thank you. You can stop whenever you like.','No pressure, probing for reasons or finishing for them.']],
 'card_labels':['AIM','SAY','AVOID'],
 'entry_branches':[['Nothing written','Check entry / connection','#245B78'],['Draft, not submitted','Keep page. See E1.','#276047'],['Submitted / uncertain','Do not resubmit. E6.','#E0001B']],
 'status_branches':[['Voice unavailable','Switch to text. E4.','#245B78'],['Explicit error','Safe to retry? E5.','#276047'],['Unclear receipt','Do not resubmit. E6.','#E0001B']],
 'incidents':[
  ['E1 / Unstable network or page will not open',[
   ['ASK','Is there a draft? Has submit been pressed? Then check the connection and entry.'],
   ['NO DRAFT','The visitor may choose another network and reopen the verified entry.'],
   ['DRAFT ONLY','Keep the page; do not refresh or clear. Explain it has not been submitted. Use an agreed draft-recovery method, or let the visitor stop. Do not route to a receipt check.'],
   ['SUBMITTED','If submit was pressed or this is uncertain, follow E6. Do not reopen to resubmit.'],
   ['STOP / LOG','Stop after one changed recovery attempt fails, or if the visitor wishes. Log entry, state and outcome to the lead.']]],
  ['E2 / NFC or QR code does not open',[
   ['CHECK','Check the card subject, any QR obstruction and the target link.'],
   ['TRY','If NFC fails, use a verified QR for the same subject. If QR fails, use only a backup entry verified by the lead.'],
   ['STOP / LOG','Stop if the alternative fails or none exists. Log touchpoint ID and symptom to the lead for material checks.']]],
  ['E3 / The page shows the wrong subject',[
   ['CHECK','Compare the product / sign, material and page; pause writing.'],
   ['TRY','With no draft, open the correct entry. If text exists, explain possible loss; do not promise automatic transfer.'],
   ['STOP / LOG','If the right entry is unavailable or still wrong, pause the material. Log shown and intended subjects to the lead.']]],
  ['E4 / Voice unavailable or transcription fails',[
   ['CHECK','Read the message and check whether any text already exists.'],
   ['TRY','Offer text and follow the page instructions to retain existing words. Try voice recovery only if supported by the confirmed version.'],
   ['STOP / LOG','After one failed recovery, or if they prefer, write or finish. Log the message and outcome to the lead.']]],
  ['E5 / An explicit submit error',[
   ['CHECK','Read the error using the lead’s agreed interpretation. An error may not mean the backend received nothing.'],
   ['TRY','Let the visitor retry only if that error is confirmed safe to retry.'],
   ['STOP / LOG','After one failed safe retry, or if receipt is uncertain, follow E6. Log time, retry count and last state to the lead.']]],
  ['E6 / Submitted, but receipt is unclear',[
   ['CHECK','Ask what happened last and read the page. No success message does not prove nothing was received.'],
   ['ON SITE','Keep the page if open; do not refresh or reopen to resubmit. Explain the uncertainty and let the visitor stop waiting.'],
   ['STOP / LOG','Stop retrying. Log time, entry, last action and any receipt ID. The lead asks the backend to check.'],
   ['STATUS','Record “unclear” and update after checking. Without a confirmed mechanism, do not claim receipt.']]]],
 'incident_note':'The lead confirms recovery rules in section 08. Do not promise unverified capabilities.',
 'record_staff_title':'A / Quick notes by field staff',
 'record_staff':[['ITEM','COMPLETE ON SITE'],['Time & subject','Time: ________ Area / entry: __________________\nSubject: ____________________________________'],['Issue & help','Issue or essential quote: _____________________\nHelp given / retries: __________________________'],['Completion','□ Independent  □ With help  □ Incomplete  □ Unclear\nLast page state: ______________________________'],['Handover','Follow-up: □ Yes □ No  Assign to: ______________\nStaff code: ________ Record ID: ________________']],
 'record_note':'The standard invitation is not “help”; extra explanation, prompting or troubleshooting is. No visitor name, phone number or full feedback is needed.',
 'record_lead_title':'B / Follow-up by the lead',
 'record_lead':[['ITEM','LEAD COMPLETES'],['Accept & assign','Accepted by / at: _____________________________\nTechnical / backend / content owner: ____________'],['Verify & close','Live receipt: □ Verified □ Unverified □ N/A\n□ Pending □ In progress □ Closed\nNext check: ________ Outcome evidence: _________']],
 'handoff':'Entry, network and voice issues go to technical support; receipt checks to backend; subjects and questions to the area owner. Escalate repeated failures or wrong subjects promptly. Hand over other notes at shift change and confirm who will follow up.',
 'setup':[['SETUP','LEAD CONFIRMS'],['People & contacts','Field lead / backup: __________________________\nTechnical / backend / content contacts: __________'],['Entries & recovery','Entries, backup links and live completion checked: ___\nDraft recovery, safe retries and wait limit: _________'],['Records & purpose','Storage / access / retention: ___________________\nAgreed purpose statement / owner: ______________']],
 'demo_title':'Brief the team before using the demo',
 'demo':'“This is a simulation. Voice uses sample text and nothing is sent.” It shows product feedback only, not all area routes. It captures no audio and does not connect to the company platform. Switching views keeps text; refresh / restart clears it, and a new voice sample may replace it.',
 'walk_title':'Three walkthroughs',
 'walk':['A new staff member finds an area, checks the subject and entry, and gives an optional invitation.','A visitor does not know what to say: find a relevant card and give a neutral prompt.','Draft but no submit when offline: E1. Submit pressed but no clear result: E6.'],
 'walk_log':'Date: ________ Participant: ________\nEach task: □ Found □ Needed a prompt □ Not found\nChanges: ________________ Owner / review: ______________',
 'quick_title':'What you see. What to do next.',
 'quick_sub':'Field quick reference / See the E number for detail. First match the area and feedback subject.',
 'quick_rows':[['WHAT YOU SEE','NEXT ACTION','WHEN / WHO'],['Entry fails; no draft','Check subject and connection. Try one verified alternative. E1 / E2','Still fails: stop and contact the lead.'],['Draft; not submitted','Keep page; do not refresh. Use agreed recovery, or let them stop. E1','No recovery: log to lead. No receipt check.'],['Submitted; unclear','Do not resubmit. Keep page and let them stop waiting. E6','Log time, entry and last action. Lead asks backend.'],['Wrong subject','Pause. Find the correct entry; explain draft-loss risks. E3','Still wrong / unavailable: pause material; tell lead.'],['Voice unavailable','Offer text. After one failed recovery, write or finish. E4','Log message and outcome to lead / technical support.'],['Explicit submit error','Retry once only if confirmed safe; uncertain receipt goes to E6. E5','Still fails: tell lead; backend checks receipt.']],
 'quick_prompt':'Not sure what to say? “You can share one thing that stood out.” If welcome: “What made you feel that way?” Do not suggest answers, answer for them or insist on more.',
 'quick_end':'Log time, area / entry, difficulty, help and last state. Lead / channel: __________________\nDemo training: sample voice, no sending; refresh clears text. Field settings: section 08.'
}}
